### ISSUE TITLE
Consider combing selectors.

### ISSUE THREAD

**Issue by JulianNorton** [tachyons-css/tachyons-skins-pseudo#3]
https://github.com/tachyons-css/tachyons-skins-pseudo/blob/5a1bb492fd47bf91239ff678712c92b5d78ed2a5/css/tachyons-skins-pseudo.css#L126

I'm wondering why the selectors are separated out between hover and focus. Is there a functional reason for this?
```
.hover-bg-yellow:hover { background-color: #ffd700; }
.hover-bg-yellow:focus { background-color: #ffd700; }
```

Why not consolidate it together like so?

```
.hover-bg-yellow:hover, .hover-bg-yellow:focus { background-color: #ffd700; }
```

The unminified file would go from 7kb to 6kb.

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
